main:
  - identifier: work
    name: Work
    url: /work
    weight: 1
  - identifier: about
    name: About
    url: /about/
    weight: 2
  - identifier: services
    name: Services
    url: /services/
    weight: 3
  - identifier: contact
    name: Contact
    url: /contact/
    weight: 4
