contact: 
  email: studio@starholden.com
  instagram: studiostarholden
  address: Studio 201 30 Brickfield Road London E3 3LT
  addressGoogleMaps: https://www.google.com/maps/place/Brickfield+Studios/@51.5205154,-0.0141243,17z/data=!3m1!4b1!4m5!3m4!1s0x48761d4e7b2c4d27:0x7eaa21aee1c680f8!8m2!3d51.5205404!4d-0.0140288
meta:
  description: "artresearch.tech"
